// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: alaya-world v0.0.0

"use client";

import { type ReactElement } from "react";
import {
  ReactorProvider,
  useReactor,
  useReactorMessage,
  ReactorView,
  type ReactorViewProps,
} from "@reactor-team/js-sdk";
import {
  MODEL_NAME,
  AlayaWorldTracks,
  type AlayaWorldOptions,
  type AlayaWorldSetPromptParams,
  type AlayaWorldSetForwardParams,
  type AlayaWorldSetStrafeParams,
  type AlayaWorldSetVerticalParams,
  type AlayaWorldSetPitchParams,
  type AlayaWorldSetYawParams,
  type AlayaWorldSetRollParams,
  type AlayaWorldSetPausedParams,
  type AlayaWorldResetParams,
  type AlayaWorldSetImageParams,
  type AlayaWorldMessage,
  type AlayaWorldStateUpdateMessage,
  type AlayaWorldImageSelectedMessage,
  type AlayaWorldPromptQueuedMessage,
  type AlayaWorldCameraMotionChangedMessage,
  type AlayaWorldPauseChangedMessage,
  type AlayaWorldStepQueuedMessage,
  type AlayaWorldRolloutResetQueuedMessage,
  type AlayaWorldRecvTrackName,
} from "./client";

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Props for the {@link AlayaWorldProvider} component.
 *
 * Derived from `ReactorProvider`'s own props, with `modelName` and
 * `modelTracks` stripped — those are supplied by this provider.
 */
export type AlayaWorldProviderProps = Omit<
  Parameters<typeof ReactorProvider>[0],
  "modelName" | "modelTracks"
>;

/**
 * Provider for the AlayaWorld model.
 *
 * Wraps {@link ReactorProvider} with `modelName` and `modelTracks` pre-configured from the
 * generated constants. Drop this near the top of your tree, then use
 * {@link useAlayaWorld} and the `useAlayaWorld<Message>` hooks below it.
 */
export function AlayaWorldProvider({
  children,
  ...rest
}: AlayaWorldProviderProps): ReactElement {
  return (
    <ReactorProvider
      {...rest}
      modelName={MODEL_NAME}
      modelTracks={[...AlayaWorldTracks]}
    >
      {children}
    </ReactorProvider>
  );
}

/**
 * Access the AlayaWorld model as typed commands bound to the nearest
 * {@link AlayaWorldProvider}.
 *
 * Returns the full action surface — every public field on the SDK's
 * `ReactorStore` (`status`, `sessionId`, `connect`, `disconnect`,
 * `sendCommand`, `uploadFile`, `publish`, `unpublish`, `reconnect`,
 * …) is exposed automatically, alongside one typed method per
 * model event.
 *
 * Fields are pulled off the store one at a time so Zustand's
 * shallow-equality selector keeps each subscription scoped — a
 * component reading only `status` doesn't re-render when
 * `sessionExpiration` changes. Future SDK releases that add new
 * store fields flow into this hook on the next codegen run with no
 * hand-edit (the field list is derived from `js-sdk`'s d.ts via
 * `loadReactorStoreFieldsFromDts` in `sdk-surface.ts`).
 */
export function useAlayaWorld() {
  const connect = useReactor((s) => s.connect);
  const connectOptions = useReactor((s) => s.connectOptions);
  const disconnect = useReactor((s) => s.disconnect);
  const downloadClipAsFile = useReactor((s) => s.downloadClipAsFile);
  const jwtToken = useReactor((s) => s.jwtToken);
  const lastError = useReactor((s) => s.lastError);
  const publish = useReactor((s) => s.publish);
  const reconnect = useReactor((s) => s.reconnect);
  const requestClip = useReactor((s) => s.requestClip);
  const requestRecording = useReactor((s) => s.requestRecording);
  const sendCommand = useReactor((s) => s.sendCommand);
  const sessionExpiration = useReactor((s) => s.sessionExpiration);
  const sessionId = useReactor((s) => s.sessionId);
  const status = useReactor((s) => s.status);
  const tracks = useReactor((s) => s.tracks);
  const unpublish = useReactor((s) => s.unpublish);
  const uploadFile = useReactor((s) => s.uploadFile);

  return {
    connect,
    connectOptions,
    disconnect,
    downloadClipAsFile,
    jwtToken,
    lastError,
    publish,
    reconnect,
    requestClip,
    requestRecording,
    sendCommand,
    sessionExpiration,
    sessionId,
    status,
    tracks,
    unpublish,
    uploadFile,
    setPrompt: (params: AlayaWorldSetPromptParams): Promise<void> =>
      sendCommand("set_prompt", params),
    setForward: (params: AlayaWorldSetForwardParams): Promise<void> =>
      sendCommand("set_forward", params),
    setStrafe: (params: AlayaWorldSetStrafeParams): Promise<void> =>
      sendCommand("set_strafe", params),
    setVertical: (params: AlayaWorldSetVerticalParams): Promise<void> =>
      sendCommand("set_vertical", params),
    setPitch: (params: AlayaWorldSetPitchParams): Promise<void> =>
      sendCommand("set_pitch", params),
    setYaw: (params: AlayaWorldSetYawParams): Promise<void> =>
      sendCommand("set_yaw", params),
    setRoll: (params: AlayaWorldSetRollParams): Promise<void> =>
      sendCommand("set_roll", params),
    setPaused: (params: AlayaWorldSetPausedParams): Promise<void> =>
      sendCommand("set_paused", params),
    step: (): Promise<void> =>
      sendCommand("step", {}),
    reset: (params: AlayaWorldResetParams): Promise<void> =>
      sendCommand("reset", params),
    setImage: (params: AlayaWorldSetImageParams): Promise<void> =>
      sendCommand("set_image", params),
    randomImage: (): Promise<void> =>
      sendCommand("random_image", {}),
  };
}

/**
 * Subscribe to any AlayaWorld message with a fully-typed handler.
 * The handler receives a discriminated AlayaWorldMessage.
 */
export function useAlayaWorldMessage(
  handler: (message: AlayaWorldMessage) => void,
): void {
  useReactorMessage((msg: unknown) =>
    handler(_unwrapMessage<AlayaWorldMessage>(msg)),
  );
}

/**
 * Subscribe to "state_update" messages only.
 * Handler receives a fully-typed AlayaWorldStateUpdateMessage.
 */
export function useAlayaWorldStateUpdate(
  handler: (message: AlayaWorldStateUpdateMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "state_update") {
      handler(m as AlayaWorldStateUpdateMessage);
    }
  });
}

/**
 * Subscribe to "image_selected" messages only.
 * Handler receives a fully-typed AlayaWorldImageSelectedMessage.
 */
export function useAlayaWorldImageSelected(
  handler: (message: AlayaWorldImageSelectedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "image_selected") {
      handler(m as AlayaWorldImageSelectedMessage);
    }
  });
}

/**
 * Subscribe to "prompt_queued" messages only.
 * Handler receives a fully-typed AlayaWorldPromptQueuedMessage.
 */
export function useAlayaWorldPromptQueued(
  handler: (message: AlayaWorldPromptQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "prompt_queued") {
      handler(m as AlayaWorldPromptQueuedMessage);
    }
  });
}

/**
 * Subscribe to "camera_motion_changed" messages only.
 * Handler receives a fully-typed AlayaWorldCameraMotionChangedMessage.
 */
export function useAlayaWorldCameraMotionChanged(
  handler: (message: AlayaWorldCameraMotionChangedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "camera_motion_changed") {
      handler(m as AlayaWorldCameraMotionChangedMessage);
    }
  });
}

/**
 * Subscribe to "pause_changed" messages only.
 * Handler receives a fully-typed AlayaWorldPauseChangedMessage.
 */
export function useAlayaWorldPauseChanged(
  handler: (message: AlayaWorldPauseChangedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "pause_changed") {
      handler(m as AlayaWorldPauseChangedMessage);
    }
  });
}

/**
 * Subscribe to "step_queued" messages only.
 * Handler receives a fully-typed AlayaWorldStepQueuedMessage.
 */
export function useAlayaWorldStepQueued(
  handler: (message: AlayaWorldStepQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "step_queued") {
      handler(m as AlayaWorldStepQueuedMessage);
    }
  });
}

/**
 * Subscribe to "rollout_reset_queued" messages only.
 * Handler receives a fully-typed AlayaWorldRolloutResetQueuedMessage.
 */
export function useAlayaWorldRolloutResetQueued(
  handler: (message: AlayaWorldRolloutResetQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<AlayaWorldMessage>(msg);
    if (m.type === "rollout_reset_queued") {
      handler(m as AlayaWorldRolloutResetQueuedMessage);
    }
  });
}

/**
 * Subscribe to a recvonly MediaStreamTrack the model publishes, by name.
 *
 * Returns `undefined` until the model emits the track, then the live track for the lifetime of the connection. `name` is constrained to the model's declared recvonly channels — use one of `AlayaWorldRecvTrackName`.
 * @param name - A recvonly track name declared by the model
 * @returns The live MediaStreamTrack, or `undefined` until received
 */
export function useAlayaWorldTrack(
  name: AlayaWorldRecvTrackName,
): MediaStreamTrack | undefined {
  return useReactor((s) => s.tracks[name]);
}

export type AlayaWorldMainVideoViewProps = Omit<ReactorViewProps, "track">;

/**
 * Render the model's "main_video" recvonly video track in a `<video>` element.
 *
 * Thin wrapper around `<ReactorView>` with `track` pre-bound. Accepts every other `ReactorViewProps` (`audioTrack`, `className`, `style`, `videoObjectFit`, `muted`, …). Must be rendered inside `<AlayaWorldProvider>`.
 */
export function AlayaWorldMainVideoView(
  props: AlayaWorldMainVideoViewProps,
): ReactElement {
  return <ReactorView {...props} track="main_video" />;
}
