// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: alaya-world v0.0.0

import { Reactor, FileRef } from "@reactor-team/js-sdk";
export { FileRef };

export const MODEL_NAME = "alaya-world" as const;
export const MODEL_VERSION = "v0.0.0" as const;

/**
 * Preset media tracks for the AlayaWorld model.
 *
 * Declared in the model's OpenAPI schema and passed to the SDK as
 * `modelTracks` so the transport can prepare the SDP offer in
 * parallel with session polling (faster first-frame latency).
 */
export const AlayaWorldTracks = [
  { name: "main_video", kind: "video", direction: "recvonly" },
] as const;

/** Track names the client can subscribe to (recvonly, from the client's perspective). */
export type AlayaWorldRecvTrackName =
  "main_video";

/** Set the scene prompt for the next 32-frame chunk without resetting the world. Requires a selected image. Emits `prompt_queued` and broadcasts `state_update` on success, or `command_error` when the prompt is empty or no image is selected. */
export interface AlayaWorldSetPromptParams {
  /**
   * Non-empty scene prompt, trimmed and sampled when the next 32-frame chunk starts. Requires an image selected by `set_image` or `random_image`.
   * @maxLength 4096
   * @default ""
   */

  prompt?: string;
}

/** Set backward or forward camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldSetForwardParams {
  /**
   * Backward (-1) to forward (1) velocity sampled when the next chunk starts and held until changed; zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  forward?: number;
}

/** Set left or right camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldSetStrafeParams {
  /**
   * Left (-1) to right (1) velocity sampled when the next chunk starts and held until changed; zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  strafe?: number;
}

/** Set down or up camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldSetVerticalParams {
  /**
   * Down (-1) to up (1) velocity sampled when the next chunk starts and held until changed; zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  vertical?: number;
}

/** Set down or up camera pitch velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldSetPitchParams {
  /**
   * Look down (-1) to up (1) velocity sampled when the next chunk starts and held until changed; zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  pitch?: number;
}

/** Set left or right camera yaw velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldSetYawParams {
  /**
   * Turn left (-1) to right (1) velocity sampled when the next chunk starts and held until changed; zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  yaw?: number;
}

/** Set counterclockwise or clockwise camera roll velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldSetRollParams {
  /**
   * Counterclockwise (-1) to clockwise (1) velocity sampled when the next chunk starts and held until changed; zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  roll?: number;
}

/** Pause before the next chunk or resume continuous generation, releasing all camera motion in either case. Resuming requires a selected image. Emits `pause_changed` and broadcasts `state_update` on success, or `command_error` when resuming without an image. */
export interface AlayaWorldSetPausedParams {
  /**
   * True pauses before the next chunk; false resumes continuous generation. Both values reset all camera velocities to zero.
   * @default false
   */

  paused?: boolean;
}

/** Queue a fresh rollout from the selected image, current prompt, and neutral camera motion. Requires a selected image. Emits `rollout_reset_queued` and broadcasts `state_update` on success, or `command_error` when no image is selected. */
export interface AlayaWorldResetParams {
  /**
   * Random seed for the fresh rollout. Use -1 to retain the active seed; a non-negative value replaces it when the reset begins.
   * @minimum -1
   * @maximum 2147483647
   * @default -1
   */

  seed?: number;
}

/** Select an uploaded image, queue a fresh rollout, and resume continuous generation. Can replace the image at any time. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when the upload is missing, too large, mislabeled, or undecodable. */
export interface AlayaWorldSetImageParams {
  /** Reference to a file uploaded via the Reactor upload protocol. */

  image: FileRef;
  /**
   * Optional scene prompt for the fresh rollout. Whitespace is trimmed; an empty value retains the current prompt or uses a generic continuation prompt when none exists.
   * @maxLength 4096
   * @default ""
   */

  prompt?: string;
}

/** Emitted when observable session state changes or a viewer connects. */
export interface AlayaWorldStateUpdateMessage {
  type: "state_update";
  /** Source of the rollout image: "uploaded", "built_in", or null before `set_image` or `random_image` succeeds. */

  image_source: "uploaded" | "built_in" | null;
  /** Selected image filename, or null before the session has an image. */

  image_name: string | null;
  /** Scene prompt queued for the next 32-frame chunk, or null before an image is selected. */

  prompt: string | null;
  /** Scene prompt used by the most recently completed chunk, or null before the rollout starts. */

  active_prompt: string | null;
  /** Random seed used when the current rollout is initialized or reset. */

  seed: number;
  /** Whether automatic chunk generation is paused before the next chunk. */

  paused: boolean;
  /** Whether `step` has queued one 32-frame chunk while paused. */

  step_queued: boolean;
  /** Whether the selected image, prompt, and seed will start a fresh rollout. */

  reset_queued: boolean;
  /** Whether the model is currently resetting or generating a chunk. */

  generating: boolean;
  /** Number of 32-frame chunks completed since the latest rollout reset. */

  completed_chunks: number;
  /** One-based chunk that will sample the queued prompt and camera motion, or null before an image is selected. */

  next_chunk: number | null;
  /** Chunk count that triggers an automatic fresh rollout from the same image. */

  max_chunks: number;
  /** Left (-1) to right (1) velocity queued for `next_chunk`; zero is neutral. */

  strafe: number;
  /** Down (-1) to up (1) velocity queued for `next_chunk`; zero is neutral. */

  vertical: number;
  /** Backward (-1) to forward (1) velocity queued for `next_chunk`; zero is neutral. */

  forward: number;
  /** Look down (-1) to up (1) velocity queued for `next_chunk`; zero is neutral. */

  pitch: number;
  /** Turn left (-1) to right (1) velocity queued for `next_chunk`; zero is neutral. */

  yaw: number;
  /** Counterclockwise (-1) to clockwise (1) velocity queued for `next_chunk`; zero is neutral. */

  roll: number;
}

/** Emitted when `set_image` or `random_image` queues a fresh rollout. */
export interface AlayaWorldImageSelectedMessage {
  type: "image_selected";
  /** Selected image source: "uploaded" for `set_image` or "built_in" for `random_image`. */

  source: "uploaded" | "built_in";
  /** Selected image filename displayed by the client for the fresh rollout. */

  filename: string;
  /** Effective non-empty scene prompt that the fresh rollout will use. */

  prompt: string;
  /** One-based chunk affected by the image selection; always 1 for a fresh rollout. */

  applies_to_chunk: number;
}

/** Emitted when `set_prompt` queues text for a forthcoming chunk. */
export interface AlayaWorldPromptQueuedMessage {
  type: "prompt_queued";
  /** Trimmed, non-empty scene prompt queued by `set_prompt`. */

  prompt: string;
  /** One-based chunk in the active rollout that will first use `prompt`. */

  applies_to_chunk: number;
}

/** Emitted when a camera command changes motion queued for a chunk. */
export interface AlayaWorldCameraMotionChangedMessage {
  type: "camera_motion_changed";
  /** Left (-1) to right (1) velocity held until another camera command changes it. */

  strafe: number;
  /** Down (-1) to up (1) velocity held until another camera command changes it. */

  vertical: number;
  /** Backward (-1) to forward (1) velocity held until another camera command changes it. */

  forward: number;
  /** Look down (-1) to up (1) velocity held until another camera command changes it. */

  pitch: number;
  /** Turn left (-1) to right (1) velocity held until another camera command changes it. */

  yaw: number;
  /** Counterclockwise (-1) to clockwise (1) velocity held until another camera command changes it. */

  roll: number;
  /** One-based chunk that will first sample the complete six-axis motion. */

  applies_to_chunk: number;
}

/** Emitted when `set_paused` changes playback and releases camera motion. */
export interface AlayaWorldPauseChangedMessage {
  type: "pause_changed";
  /** Whether automatic generation will stop before the next chunk. */

  paused: boolean;
  /** Whether all six persistent camera velocities were reset to zero; always true. */

  camera_motion_released: boolean;
}

/** Emitted when `step` queues one chunk while generation is paused. */
export interface AlayaWorldStepQueuedMessage {
  type: "step_queued";
  /** One-based chunk in the active rollout that the queued step will generate. */

  applies_to_chunk: number;
}

/** Emitted when a manual or automatic reset queues a fresh rollout. */
export interface AlayaWorldRolloutResetQueuedMessage {
  type: "rollout_reset_queued";
  /** Reset source: "manual" for `reset` or "automatic_chunk_limit" after `max_chunks` completes. */

  trigger: "manual" | "automatic_chunk_limit";
  /** Random seed that will initialize the queued fresh rollout. */

  seed: number;
  /** Number of completed chunks in the rollout being replaced. */

  completed_chunks: number;
  /** One-based chunk affected by the reset; always 1 for a fresh rollout. */

  applies_to_chunk: number;
}

export type AlayaWorldMessage =
  | AlayaWorldStateUpdateMessage
  | AlayaWorldImageSelectedMessage
  | AlayaWorldPromptQueuedMessage
  | AlayaWorldCameraMotionChangedMessage
  | AlayaWorldPauseChangedMessage
  | AlayaWorldStepQueuedMessage
  | AlayaWorldRolloutResetQueuedMessage;

/**
 * Options for creating a AlayaWorldModel (model name is set automatically).
 *
 * Derived from `Reactor`'s own constructor options with `modelName`
 * and `modelTracks` removed — those are supplied by this class.
 * Any new option the SDK adds appears here automatically on the
 * next `defaultSdkVersion` bump.
 */
export type AlayaWorldOptions = Omit<
  ConstructorParameters<typeof Reactor>[0],
  "modelName" | "modelTracks"
>;

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Strongly-typed client for the AlayaWorld model.
 *
 * Extends {@link Reactor} with the model name (and modelTracks) baked into the
 * constructor, so every public method on Reactor — `connect`, `disconnect`,
 * `sendCommand`, `on`/`off`, `getStats`, `publishTrack`/`unpublishTrack`,
 * etc. — is reachable directly on the instance. The schema-derived sugar
 * below adds typed wrappers for every declared event, message, and track.
 */

export class AlayaWorldModel extends Reactor {
  constructor(options?: AlayaWorldOptions) {
    super({
      ...options,
      modelName: MODEL_NAME,
      modelTracks: [...AlayaWorldTracks],
    });
  }

  /** @deprecated The model client now extends `Reactor` directly — call methods on `this` instead. This accessor returns `this` for backwards compatibility and will be removed in a future major release. */

  get reactor(): this {
    return this;
  }

  /**
   * Set the scene prompt for the next 32-frame chunk without resetting the world. Requires a selected image. Emits `prompt_queued` and broadcasts `state_update` on success, or `command_error` when the prompt is empty or no image is selected.
   * @param params - Set the scene prompt for the next 32-frame chunk without resetting the world. Requires a selected image. Emits `prompt_queued` and broadcasts `state_update` on success, or `command_error` when the prompt is empty or no image is selected.
   */

  async setPrompt(params: AlayaWorldSetPromptParams): Promise<void> {
    await this.sendCommand("set_prompt", params);
  }

  /**
   * Set backward or forward camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Set backward or forward camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async setForward(params: AlayaWorldSetForwardParams): Promise<void> {
    await this.sendCommand("set_forward", params);
  }

  /**
   * Set left or right camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Set left or right camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async setStrafe(params: AlayaWorldSetStrafeParams): Promise<void> {
    await this.sendCommand("set_strafe", params);
  }

  /**
   * Set down or up camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Set down or up camera velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async setVertical(params: AlayaWorldSetVerticalParams): Promise<void> {
    await this.sendCommand("set_vertical", params);
  }

  /**
   * Set down or up camera pitch velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Set down or up camera pitch velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async setPitch(params: AlayaWorldSetPitchParams): Promise<void> {
    await this.sendCommand("set_pitch", params);
  }

  /**
   * Set left or right camera yaw velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Set left or right camera yaw velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async setYaw(params: AlayaWorldSetYawParams): Promise<void> {
    await this.sendCommand("set_yaw", params);
  }

  /**
   * Set counterclockwise or clockwise camera roll velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Set counterclockwise or clockwise camera roll velocity for forthcoming chunks. Requires a selected image. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async setRoll(params: AlayaWorldSetRollParams): Promise<void> {
    await this.sendCommand("set_roll", params);
  }

  /**
   * Pause before the next chunk or resume continuous generation, releasing all camera motion in either case. Resuming requires a selected image. Emits `pause_changed` and broadcasts `state_update` on success, or `command_error` when resuming without an image.
   * @param params - Pause before the next chunk or resume continuous generation, releasing all camera motion in either case. Resuming requires a selected image. Emits `pause_changed` and broadcasts `state_update` on success, or `command_error` when resuming without an image.
   */

  async setPaused(params: AlayaWorldSetPausedParams): Promise<void> {
    await this.sendCommand("set_paused", params);
  }

  /** Queue exactly one 32-frame chunk while continuous generation is paused. Requires a selected image and `paused=true`. Emits `step_queued` and broadcasts `state_update` on success, or `command_error` when either precondition is missing. */

  async step(): Promise<void> {
    await this.sendCommand("step", {});
  }

  /**
   * Queue a fresh rollout from the selected image, current prompt, and neutral camera motion. Requires a selected image. Emits `rollout_reset_queued` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   * @param params - Queue a fresh rollout from the selected image, current prompt, and neutral camera motion. Requires a selected image. Emits `rollout_reset_queued` and broadcasts `state_update` on success, or `command_error` when no image is selected.
   */

  async reset(params: AlayaWorldResetParams): Promise<void> {
    await this.sendCommand("reset", params);
  }

  /**
   * Select an uploaded image, queue a fresh rollout, and resume continuous generation. Can replace the image at any time. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when the upload is missing, too large, mislabeled, or undecodable.
   * @param params - Select an uploaded image, queue a fresh rollout, and resume continuous generation. Can replace the image at any time. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when the upload is missing, too large, mislabeled, or undecodable.
   */

  async setImage(params: AlayaWorldSetImageParams): Promise<void> {
    await this.sendCommand("set_image", params);
  }

  /** Select a built-in image and its matching prompt, queue a fresh rollout, and resume continuous generation. Valid when built-in examples are configured. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when no usable image or prompt is available. */

  async randomImage(): Promise<void> {
    await this.sendCommand("random_image", {});
  }

  /**
   * Subscribe to typed model messages.
   * @param handler - Called with a discriminated AlayaWorldMessage
   * @returns Unsubscribe function
   */

  onMessage(handler: (message: AlayaWorldMessage) => void): () => void {
    const wrappedHandler = (raw: unknown) => {
      handler(_unwrapMessage<AlayaWorldMessage>(raw));
    };
    this.on("message", wrappedHandler);
    return () => this.off("message", wrappedHandler);
  }

  /**
   * Subscribe to "state_update" messages only.
   * @returns Unsubscribe function
   */

  onStateUpdate(handler: (message: AlayaWorldStateUpdateMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "state_update") handler(msg as AlayaWorldStateUpdateMessage);
    });
  }

  /**
   * Subscribe to "image_selected" messages only.
   * @returns Unsubscribe function
   */

  onImageSelected(handler: (message: AlayaWorldImageSelectedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "image_selected") handler(msg as AlayaWorldImageSelectedMessage);
    });
  }

  /**
   * Subscribe to "prompt_queued" messages only.
   * @returns Unsubscribe function
   */

  onPromptQueued(handler: (message: AlayaWorldPromptQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "prompt_queued") handler(msg as AlayaWorldPromptQueuedMessage);
    });
  }

  /**
   * Subscribe to "camera_motion_changed" messages only.
   * @returns Unsubscribe function
   */

  onCameraMotionChanged(handler: (message: AlayaWorldCameraMotionChangedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "camera_motion_changed") handler(msg as AlayaWorldCameraMotionChangedMessage);
    });
  }

  /**
   * Subscribe to "pause_changed" messages only.
   * @returns Unsubscribe function
   */

  onPauseChanged(handler: (message: AlayaWorldPauseChangedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "pause_changed") handler(msg as AlayaWorldPauseChangedMessage);
    });
  }

  /**
   * Subscribe to "step_queued" messages only.
   * @returns Unsubscribe function
   */

  onStepQueued(handler: (message: AlayaWorldStepQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "step_queued") handler(msg as AlayaWorldStepQueuedMessage);
    });
  }

  /**
   * Subscribe to "rollout_reset_queued" messages only.
   * @returns Unsubscribe function
   */

  onRolloutResetQueued(handler: (message: AlayaWorldRolloutResetQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "rollout_reset_queued") handler(msg as AlayaWorldRolloutResetQueuedMessage);
    });
  }

  /**
   * Subscribe to the "main_video" recvonly video track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainVideo(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_video") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }
}
